# Note : this causes annoying psych warnings under Ruby 1.9.2-p180; to fix, upgrade to 1.9.3
begin
  require 'bundler'
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

require 'rake/dsl_definition'
require 'rake'
include Rake::DSL

require "./lib/annotate"

# want other tests/tasks run by default? Add them to the list
task :default => [:spec]

# mg ("minimalist gems") defines rake tasks:
#
# rake gem
#   Build gem into dist/
#
# rake gem:publish
#   Push the gem to RubyGems.org
#
# rake gem:install
#   Build and install as local gem
#
# rake package
#   Build gem and tarball into dist/
begin
  require 'mg'
rescue LoadError
  abort "Please `gem install mg`"
end
MG.new("annotate.gemspec")

task :default => :spec

require "rspec/core/rake_task" # RSpec 2.0
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = ['spec/*_spec.rb', 'spec/**/*_spec.rb']
end

require 'rdoc/task'
RDoc::Task.new do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "annotated_models #{Annotate.version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

task :integration_environment do
  require './spec/spec_helper'
end

namespace :gemsets do
  desc "Completely empty any gemsets used by scenarios, so they'll be perfectly clean on the next run."
  task :empty => [:integration_environment, :'templates:rebuild'] do
    Annotate::Integration::SCENARIOS.each do |test_rig, base_dir, test_name|
      Annotate::Integration.empty_gemset(test_rig)
    end
  end
end
task :clobber => :'gemsets:empty'

namespace :integration do
  desc "Remove any cruft generated by manual debugging runs which is .gitignore'd."
  task :clean => :integration_environment do
    Annotate::Integration.nuke_all_cruft
  end

  desc "Reset any changed files, and remove any untracked files in spec/integration/*/, plus run integration:clean."
  task :clobber => [:integration_environment, :'integration:clean'] do
    Annotate::Integration.reset_dirty_files
    Annotate::Integration.clear_untracked_files
  end
end
task :clobber => :'integration:clobber'

namespace :templates do
  desc "Rebuild templates used for interactive debugging of integration scenarios."
  task :rebuild => :integration_environment do
    Annotate::Integration::SCENARIOS.each do |test_rig, base_dir, test_name|
      puts "Compiling interactive-debugging templates for #{test_name}..."
      # Compile our debugging templates...
      Annotate::Integration.compile_templates(base_dir, test_rig, true)
    end
  end
end
